Add --config switch
thegeeklab/drone-docker-buildx pull request #32
Opened 2021-07-06 16:35 UTC by aspriddell

Closes #31 through the addition of `buildkit_config` setting in .drone.yml

2021-07-06 19:51 UTC, xoxys commented
During the review, I saw we have already a way to use insecure registries https://github.com/thegeeklab/drone-docker-buildx/blob/main/plugin/docker.go#L175 Does it not work for you?

2021-07-06 20:14 UTC, xoxys requested changes
In case, we still want to add a generic config file option:

I would like to add a check to verify that the file exist if specified, something like https://github.com/thegeeklab/drone-github-comment/blob/main/plugin/utils.go#L13

The right place would be https://github.com/thegeeklab/drone-docker-buildx/blob/29f170779747960b32b27216fb7dd538881f401d/plugin/impl.go#L79

Something like this:

```
if daemon.BuildkitConfig != "" {
    if _, err := os.Stat(settings.Daemon.BuildkitConfig); err != nil && os.IsNotExist(err) {
        return fmt.Errorf("given buildkit config file not found")
    }
}
```

2021-07-06 20:59 UTC, aspriddell commented
> During the review, I saw that we have already a way to use insecure registries https://github.com/thegeeklab/drone-docker-buildx/blob/main/plugin/docker.go#L175 Does it not work for you?

just checked my previous builds and it doesn't seem to work with it:
![image](https://user-images.githubusercontent.com/10289119/124666077-6a572c00-dea5-11eb-9010-1fabaa8b37da.png)

as for the changes i'll get to them later on

2021-07-06 21:07 UTC, xoxys commented
Hmm and you have set the required settings in your drone config?

2021-07-07 06:20 UTC, aspriddell commented on cmd/drone-docker-buildx/config.go
> +			Destination: &settings.Daemon.BuildxConfig,
resolved in a917fbe

2021-07-07 08:47 UTC, aspriddell commented
> Hmm and you have set the required settings in your drone config?

yes, insecure: true and it's also used in the initial config as `--insecure-registry`

2021-07-08 06:59 UTC, xoxys approved these changes

2021-07-08 07:00 UTC, merged

2021-07-08 07:00 UTC, xoxys commented
Thanks again!